### ISSUE TITLE
Make README more understandable

### ISSUE THREAD

**Issue by shruthivis** [isblab/EASAL#3]
1. What is Jwalk? Link to it 
2. Say what each step is doing. What are the command line arguments used? E.g. 32  in step 2 and 4 in step 3. 
3. Names of files need to have linker-cutoff, number of crosslinks for unambiguous retrieval. 
4. Need shell script that was run for all the variations of cutoffs and number of crosslinks etc. 
5. Remove older folders e.g. EASAL-dev

**Comment by muskaan9jindal** [comment]
These changes are done.
